const DATA = [
  { code: 'Backquote', key: ['`', '~', 'ё', 'Ё'] },
  { code: 'Digit1', key: ['1', '!', '1', '!'] },
  { code: 'Digit2', key: ['2', '@', '2', '"'] },
  { code: 'Digit3', key: ['3', '#', '3', '№'] },
  { code: 'Digit4', key: ['4', '$', '4', ';'] },
  { code: 'Digit5', key: ['5', '%', '5', '%'] },
  { code: 'Digit6', key: ['6', '^', '6', '?'] },
  { code: 'Digit7', key: ['7', '&', '7', '?'] },
  { code: 'Digit8', key: ['8', '*', '8', '*'] },
  { code: 'Digit9', key: ['9', '(', '9', '('] },
  { code: 'Digit0', key: ['0', ')', '0', ')'] },
  { code: 'Minus', key: ['-', '_', '-', '_'] },
  { code: 'Equal', key: ['=', '+', '=', '+'] },
  { code: 'Backspace', key: 'Backspace' },
  { code: 'Tab', key: 'Tab' },
  { code: 'KeyQ', key: ['q', 'Q', 'й', 'Й'] },
  { code: 'KeyW', key: ['w', 'W', 'ц', 'Ц'] },
  { code: 'KeyE', key: ['e', 'E', 'у', 'У'] },
  { code: 'KeyR', key: ['r', 'R', 'к', 'К'] },
  { code: 'KeyT', key: ['t', 'T', 'е', 'Е'] },
  { code: 'KeyY', key: ['y', 'Y', 'н', 'Н'] },
  { code: 'KeyU', key: ['u', 'U', 'г', 'Г'] },
  { code: 'KeyI', key: ['i', 'I', 'ш', 'Ш'] },
  { code: 'KeyO', key: ['o', 'O', 'щ', 'Щ'] },
  { code: 'KeyP', key: ['p', 'P', 'з', 'З'] },
  { code: 'BracketRight', key: [']', '}', 'ъ', 'Ъ'] },
  { code: 'BracketLeft', key: ['[', '{', 'х', 'Х'] },
  { code: 'Backslash', key: ['\\', '|', '\\', '/'] },
  { code: 'Delete', key: 'Delete' },
  { code: 'CapsLock', key: 'CapsLock' },
  { code: 'KeyA', key: ['a', 'A', 'ф', 'Ф'] },
  { code: 'KeyS', key: ['s', 'S', 'ы', 'Ы'] },
  { code: 'KeyD', key: ['d', 'D', 'в', 'В'] },
  { code: 'KeyF', key: ['f', 'F', 'а', 'А'] },
  { code: 'KeyG', key: ['g', 'G', 'п', 'П'] },
  { code: 'KeyH', key: ['h', 'H', 'р', 'Р'] },
  { code: 'KeyJ', key: ['j', 'J', 'о', 'О'] },
  { code: 'KeyK', key: ['k', 'K', 'л', 'Л'] },
  { code: 'KeyL', key: ['l', 'L', 'д', 'Д'] },
  { code: 'Semicolon', key: [';', ':', 'ж', 'Ж'] },
  { code: 'Quote', key: ["'", '"', 'э', 'Э'] },
  { code: 'Enter', key: 'Enter' },
  { code: 'ShiftLeft', key: 'Shift' },
  { code: 'KeyZ', key: ['z', 'Z', 'я', 'Я'] },
  { code: 'KeyX', key: ['x', 'X', 'ч', 'Ч'] },
  { code: 'KeyC', key: ['c', 'C', 'с', 'С'] },
  { code: 'KeyV', key: ['v', 'V', 'м', 'М'] },
  { code: 'KeyB', key: ['b', 'B', 'и', 'И'] },
  { code: 'KeyN', key: ['n', 'N', 'т', 'Т'] },
  { code: 'KeyM', key: ['m', 'M', 'ь', 'Ь'] },
  { code: 'Comma', key: [',', ',', 'б', 'Б'] },
  { code: 'Period', key: ['.', '.', 'ю', 'Ю'] },
  { code: 'Slash', key: ['/', '?', '.', ','] },
  { code: 'ArrowUp', key: '&#8593' },
  { code: 'ShiftRight', key: 'Shift' },
  { code: 'ControlLeft', key: 'Ctrl' },
  { code: 'Meta', key: 'Win' },
  { code: 'AltLeft', key: 'Alt' },
  { code: 'Space', key: ' ' },
  { code: 'AltRight', key: 'Alt' },
  { code: 'ArrowLeft', key: '&#8592' },
  { code: 'ArrowDown', key: '&#8595' },
  { code: 'ArrowRight', key: '&#8594' },
  { code: 'ControlRight', key: 'Ctrl' },
];

export default DATA;
